[theme]
primaryColor = "#4CAF50"  # Cor principal dos elementos interativos
backgroundColor = "#FFFFFF"  # Cor de fundo do app
secondaryBackgroundColor = "#F0F2F6"  # Cor de fundo para áreas secundárias
textColor = "#333333"  # Cor do texto principal
font = "sans serif"  # Fonte do app (opções: "sans serif", "serif", "monospace")